[project]
version = '1.2.0'
name = 'pytest-pt'
description = 'pytest plugin to use *.pt files as tests'
authors = [
    { name = 'Curt J. Sampson', email = 'cjs@cynic.net' },
]
license = 'CC0-1.0'
readme = 'README.md'
urls.homepage = 'https://github.com/cynic-net/pytest-pt'
urls.source = 'https://github.com/cynic-net/pytest-pt'
urls.tracker = 'https://github.com/cynic-net/pytest-pt/issues'
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'Framework :: Pytest',
    'Topic :: Software Development :: Testing',
    'Programming Language :: Python :: 3 :: Only',
]

requires-python = '>=3.6'
dependencies = ['pytest']

[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[tool.setuptools.packages]
find = { where = ['src'] }

[tool.setuptools]
#   The packages.find specification above, for whatever reason, ignores all
#   top-level modules (i.e., `*.py` files that can be imported). We work
#   around this by explicitly adding our top-level module to py-modules.
#   (Note that this must be a Python module name, not a filename.) This
#   configuration directive is mentioned but not documented, but it seems
#   to add additional modules to the list that `packages.find` comes up with.
py-modules = ['pytest_pt']

#   This builds a `pytet_pt-$VER.dist-info/entry_points.txt` file with a a
#   `[pytest11]` section read by pytest to see what it should automatically
#   import. (The auto-import can be suppressed with `-p no:pytest_pt`,
#   PYTEST_DISABLE_PLUGIN_AUTOLOAD, etc.) For more, see:
#   • https://packaging.python.org/en/latest/specifications/entry-points/
#   • https://docs.pytest.org/en/stable/how-to/plugins.html#disabling-plugins-from-autoloading
#   • https://docs.pytest.org/en/stable/how-to/writing_plugins.html#making-your-plugin-installable-by-others
[project.entry-points.pytest11]
pytest_pt = 'pytest_pt'

#   This is used by pytest ≥6.0. Pytest 5.x does not read pyproject.toml
#   files, and so is configured separately in tox.ini.
[tool.pytest.ini_options]
testpaths = ['tsrc']
