#!/usr/bin/env bash
set -euo pipefail

####################################################################
#   Functions

die() {
    local exitcode="$1"; shift
    echo 1>&2 "ERROR:" "$@"
    exit $exitcode
}

clean_big() {
    clean_small     # make sure we don't miss anything
    local cleandirs=(.build/)
    echo "───── cleaning ${cleandirs[@]}"
    rm -rf ${cleandirs[@]/#/$PROJDIR/}
}

clean_small() {
    local cleandirs=(.tox/ ./src/pytest_pt.egg-info/)
    echo "───── cleaning ${cleandirs[@]}"
    rm -rf ${cleandirs[@]/#/$PROJDIR/}
}

tox_python_versions() {
    #   Extract a list of all Python versions (major.minor number only)
    #   that tox.ini is testing. `tox -a` will return a list of all
    #   combinations like `py3.11-pytest8`; for all lines starting
    #   with `pyM.n` we extract just the `M.n` and print the unique
    #   values in sorted order.
    tox -a | sed -n -e '/^py.*-pytest/{ s/^py//; s/-.*//; p }' \
        | sort -t . -k 2 -n | uniq
}

install_pythons() {
    mise --version >/dev/null || die 9 \
        'mise not found: try `curl https://mise.run | sh`'

    local v vers=( $(tox_python_versions) )
    local v overs=() nvers=()
    for v in ${vers[@]}; do
        #   No Python 2 support, so we can compare just the minor ver.
        #   Versions older than 3.9 need to be built because we have
        #   no GitHub binaries and/or attestations for them.
        [[ ${v/3./} -lt 9 ]] && overs+=("$v") || nvers+=("$v")
    done

    echo "───── Building/confirming older Pythons ${overs[@]}"
    MISE_PYTHON_COMPILE=1 mise install -q ${overs[@]/#/python@}
    echo "───── Installing/confirming newer Pythons ${nvers[@]}"
    mise install -q ${nvers[@]/#/python@}
}

test_tox() {
    local v vers=( $(tox_python_versions) )
    echo "───── tox path setup: ${vers[@]}"
    for v in ${vers[@]}; do
        #   Horrible hack to get tox to be able to use our mise Pythons.
        PATH="$(mise where ${v/#/python@})/bin":"$PATH"
    done
    echo "───── tox" "$@"
    tox "$@"
}

####################################################################
#   Main

PROJDIR=$(cd "$(dirname "$0")" && pwd -P)

#   -C or -c options to clean must be at start. Use -- -c to pass to tox.
while [[ $# -gt 0 ]]; do case "$1" in
    -C)             shift; clean_big;;
    -c)             shift; clean_small;;
    *)              break;;
esac; done

cd "$PROJDIR"
. ./pactivate -q
install_pythons
test_tox "$@"
