[project]
version = '0.0.0'
name = 'carttest'
description = 'Test against Cartesian products of Python and package versions.'
authors = [
    { name = 'Curt J. Sampson', email = 'cjs@cynic.net'
    , name = 'Nishant Rodrigues', email = 'nishantjr@gmail.com'
    }
]
requires-python = '>=3.6'

[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'
